version: "3.9"
services:

  # Flink Cluster
  # ===========================================================================
  job-cluster:
    image: streaming-job
    ports:
      - "8081:8081"
    command: job-cluster --job-classname ${FLINK_JOB} -Djobmanager.rpc.address=job-cluster ${FLINK_JOB_ARGUMENTS}
    networks:
      - devsandbox
      - observabilitysandbox

  taskmanager:
    image: streaming-job
    command: task-manager -Djobmanager.rpc.address=job-cluster
    networks:
      - devsandbox
      - observabilitysandbox

  # Zookeeper
  # ===========================================================================
  zoo1:
    image: zookeeper:3.4.9
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
      # volumes:
      # - ./persistent_volumes/zoo1/data:/data
      # - ./persistent_volumes/zoo1/datalog:/datalog
    networks:
      - devsandbox
      - observabilitysandbox

  # Minio for Checkpointing and HA
  # ===========================================================================
  minio-service:
    image: minio/minio:RELEASE.2018-11-15T01-26-07Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      - devsandbox
      - observabilitysandbox

  miniosetup:
    image: minio/mc
    depends_on:
      - minio-service
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://minio-service:9000 minio minio123;
      /usr/bin/mc mb myminio/state;
      /usr/bin/mc mb myminio/highavailability;
      exit 0;
      "
    networks:
      - devsandbox
      - observabilitysandbox

networks:
  devsandbox:
    name: devsandbox
    external: true
  observabilitysandbox:
    name: observabilitysandbox
    external: true